Repository couchbase/couchbase-lite-android, pull requests merged in 2018-04, with the labels that each got.

#1694 Fixed #1963 - DB023 - Crazy amount of dbListenerTokens - makes the DB…
  shared/src/main/java/com/couchbase/lite/LiveQuery.java
Labels: waffle:in progress

#1692 Fixed #1691 - Database.getPath has return type as File which is diffe…
  android/CouchbaseLite/src/androidTest/java/com/couchbase/lite/DatabaseTest.java
  shared/src/main/java/com/couchbase/lite/AbstractDatabase.java
Labels: in progress, review, waffle:in progress

#1695 [docs] updates
  android/CouchbaseLite/src/androidTest/java/com/couchbase/lite/MigrationTest.java
  android/CouchbaseLite/src/androidTest/java/com/couchbase/lite/api/DatabaseAPITest.java
  docs/modules/ROOT/pages/java.adoc
Labels: in progress, review, waffle:in progress

#1697 Fixed #1696 - Add 2.1: ReplicatorConfiguration.resetCheckpoint
  android/CouchbaseLite/src/androidTest/java/com/couchbase/lite/BaseReplicatorTest.java
  android/CouchbaseLite/src/androidTest/java/com/couchbase/lite/ReplicatorWithSyncGatewayDBTest.java
  android/CouchbaseLite/src/ce/java/com/couchbase/lite/ReplicatorConfiguration.java
  shared/src/main/java/com/couchbase/lite/Replicator.java
Labels: in progress, review, waffle:in progress

#1703 Fixed #1702 - 2.x: ValueIndexItem.expression(Expression) is missing
  android/CouchbaseLite/src/androidTest/java/com/couchbase/lite/DatabaseTest.java
  shared/src/main/java/com/couchbase/lite/ValueIndexItem.java
Labels: in progress, waffle:in progress

#1704 Fixed #1700 - 2.1: incorrect implementation in Performance test tool
  tools/perftest/.idea/caches/build_file_checksums.ser
  tools/perftest/.idea/codeStyles/Project.xml
  tools/perftest/.idea/misc.xml
  tools/perftest/app/build.gradle
  tools/perftest/app/src/main/java/com/couchbase/perftest/DocPerfTest.java
  tools/perftest/app/src/main/java/com/couchbase/perftest/DocSavePerfTest.java
  tools/perftest/app/src/main/java/com/couchbase/perftest/PerfTest.java
  tools/perftest/app/src/main/java/com/couchbase/perftest/PushPerfTest.java
  tools/perftest/app/src/main/java/com/couchbase/perftest/QueryPerfTest.java
  tools/perftest/app/src/main/java/com/couchbase/perftest/TunesPerfTest.java
  tools/perftest/build.gradle
  tools/perftest/gradle/wrapper/gradle-wrapper.properties
Labels: in progress, waffle:in progress

#1705 Fixed #1699 - 2.1: throw InvalidOperationException in case of failing…
  shared/src/main/java/com/couchbase/lite/Replicator.java
Labels: waffle:in progress

#1707 Fixed #1706 - database.save is not throwing couchbaseliteException in…
  android/CouchbaseLite/build.gradle
  android/CouchbaseLite/proguard-rules.pro
Labels: in progress, waffle:in progress

#1716 Fixed #1711 - 2.1 make synchronized resetCheckpoint and move flag int…
  android/CouchbaseLite/src/ce/java/com/couchbase/lite/ReplicatorConfiguration.java
  shared/src/main/java/com/couchbase/lite/Replicator.java
Labels: in progress, waffle:in progress

#1726 fixed #1725 - 2.1: Android : Replication does not start
  android/CouchbaseLite/build.gradle
Labels: in progress, waffle:in progress
