Repository couchbase/couchbase-lite-android, pull requests merged in 2018-03, with the labels that each got.

#1624 fixed #1623 - 2.0: Blob.getContent() should throw IllegalStateExcepti…
  android/CouchbaseLite/src/androidTest/java/com/couchbase/lite/DatabaseTest.java
  shared/src/main/java/com/couchbase/lite/Blob.java
  shared/src/main/java/com/couchbase/lite/CouchbaseLiteRuntimeException.java
Labels: in progress, review

#1626 Fixed #1625 - 2.0: FLSharedKeys thread safety
  shared/src/main/java/com/couchbase/lite/Result.java
Labels: in progress, review

#1631 Fixed #1630 - 2.0: make public Index interface
  shared/src/main/java/com/couchbase/lite/Index.java
Labels: review

#1643 Fixed #1629 - CBL android does not work with self signed certs (Empty…
  shared/src/main/java/com/couchbase/lite/internal/replicator/CBLWebSocket.java
  shared/src/main/java/okhttp3/internal/tls/CustomHostnameVerifier.java
Labels: review

#1648 Fixed #1640 - 2.0: port testPullConflictDeleteWins_SG unit test
  android/CouchbaseLite/src/androidTest/java/com/couchbase/lite/ReplicatorWithSyncGatewayDBTest.java
  shared/src/main/java/com/couchbase/lite/URLEndpoint.java
  shared/src/main/java/com/couchbase/lite/internal/replicator/CBLWebSocket.java
Labels: review

#1650 Fixed #1649 - 2.0: API update: Database.getCount() returns long inste…
  shared/src/main/java/com/couchbase/lite/AbstractDatabase.java
Labels: review

#1655 Fixed #1654 - 2.0: update Document.selectConflictingRevision()
  shared/src/main/java/com/couchbase/lite/Document.java
Labels: review

#1656 Fixed #1652 - App crash with deleteDocument with concurrencyControl
  android/CouchbaseLite/src/androidTest/java/com/couchbase/lite/DatabaseTest.java
  android/CouchbaseLite/src/androidTest/java/com/couchbase/lite/LoadTest.java
  shared/src/main/java/com/couchbase/lite/AbstractDatabase.java
  shared/src/main/java/com/couchbase/lite/Document.java
Labels: review

#1658 Fixed selectConflictRevision()
  shared/src/main/java/com/couchbase/lite/AbstractDatabase.java
  shared/src/main/java/com/couchbase/lite/Document.java
Labels: review

#1661 Fixed #1647 - 2.0: Review Error code, message and Exceptions
  android/CouchbaseLite/src/androidTest/java/com/couchbase/lite/ConcurrencyTest.java
  android/CouchbaseLite/src/androidTest/java/com/couchbase/lite/DatabaseTest.java
  android/CouchbaseLite/src/androidTest/java/com/couchbase/lite/ReplicatorWithSyncGatewaySSLTest.java
  android/CouchbaseLite/src/androidTest/java/com/couchbase/lite/URLEndpointTest.java
  shared/src/main/java/com/couchbase/lite/AbstractDatabase.java
  shared/src/main/java/com/couchbase/lite/Blob.java
  shared/src/main/java/com/couchbase/lite/CBLError.java
  shared/src/main/java/com/couchbase/lite/CBLStatus.java
  shared/src/main/java/com/couchbase/lite/CouchbaseLiteRuntimeException.java
  shared/src/main/java/com/couchbase/lite/Document.java
  shared/src/main/java/com/couchbase/lite/LiveQuery.java
  shared/src/main/java/com/couchbase/lite/URLEndpoint.java
Labels: review

#1666 add asciidoc tags.
  android/CouchbaseLite/src/androidTest/java/com/couchbase/lite/api/DatabaseAPITest.java
  android/CouchbaseLite/src/androidTest/java/com/couchbase/lite/api/DocumentAPITest.java
  android/CouchbaseLite/src/androidTest/java/com/couchbase/lite/api/FullTextSearchAPITest.java
  android/CouchbaseLite/src/androidTest/java/com/couchbase/lite/api/QueryAPITest.java
  android/CouchbaseLite/src/androidTest/java/com/couchbase/lite/api/ReplicationAPITest.java
Labels: review

#1668 Fixed #1667 - 2.0: Review Error message
  shared/src/main/java/com/couchbase/lite/AbstractDatabase.java
  shared/src/main/java/com/couchbase/lite/Blob.java
  shared/src/main/java/com/couchbase/lite/CBLStatus.java
  shared/src/main/java/com/couchbase/lite/Fleece.java
  shared/src/main/java/com/couchbase/lite/URLEndpoint.java
Labels: review

#1669 asciidoc docs
  android/CouchbaseLite/src/androidTest/java/com/couchbase/lite/api/ReplicationAPITest.java
  docs/antora.yml
  docs/modules/ROOT/_attributes.adoc
  docs/modules/ROOT/assets/images/attach_replicated.png
  docs/modules/ROOT/pages/_attributes.adoc
  docs/modules/ROOT/pages/java.adoc
Labels: review

#1681 [docs]
  docs/modules/ROOT/pages/java.adoc
  docs/modules/ROOT/pages/release-notes.adoc
Labels: in progress, review, waffle:in progress

#1686 Fixed #1665 - Exception thrown openDatabase
  android/CouchbaseLite/build.gradle
  android/CouchbaseLite/proguard-rules.pro
Labels: in progress, review, waffle:in progress
