Repository couchbase/couchbase-lite-android, pull requests merged in 2019-01, with the labels that each got.

#1806 #1084 Use lazy deserialization for replication filters.
  shared/src/main/java/com/couchbase/lite/AbstractReplicator.java
  shared/src/main/java/com/couchbase/lite/Document.java
  shared/src/main/java/com/couchbase/lite/MutableDocument.java
Labels: in progress, review

#1807 Verify Purging triggers Database Changed Event.
  android/CouchbaseLite/src/androidTest/java/com/couchbase/lite/DocumentTest.java
Labels: in progress, review

#1816 Change domains type of the Console Logger to EnumSet.
  android/CouchbaseLite/src/main/java/com/couchbase/lite/ConsoleLogger.java
  shared/src/main/java/com/couchbase/lite/LogDomain.java
Labels: in progress, review, waffle:in progress

#1822 test: check custom logging
  android/CouchbaseLite/src/androidTest/java/com/couchbase/lite/LogTest.java
Labels: in progress, review, waffle:in progress

#1815 #1785 Test retrieving boolean value from result toMap()
  android/CouchbaseLite/src/androidTest/java/com/couchbase/lite/QueryTest.java
Labels: review

#1832 feat: add the header information
  shared/src/main/java/com/couchbase/lite/FileLogger.java
Labels: in progress, review, waffle:in progress

#1833 Add .travis.yml
  .travis.yml
Labels: in progress, review, waffle:in progress

#1828 test: add file logging tests
  android/CouchbaseLite/src/androidTest/java/com/couchbase/lite/LogTest.java
Labels: in progress, review, waffle:in progress

#1829 test: add remaining file logging unit tests
  android/CouchbaseLite/src/androidTest/java/com/couchbase/lite/LogTest.java
Labels: in progress, review, waffle:in progress

#1831 test: check non-ASCII string in logs
  android/CouchbaseLite/src/androidTest/java/com/couchbase/lite/LogTest.java
Labels: in progress, review, waffle:in progress

#1837 Feat/debug log
  android/CouchbaseLite/src/androidTest/java/com/couchbase/lite/LogTest.java
  shared/src/main/java/com/couchbase/lite/internal/support/Log.java
Labels: in progress, review, waffle:in progress

#1843 Add annotation package
  android/CouchbaseLite/build.gradle
Labels: in progress, review, waffle:in progress

#1836 Feature/query clause validate null
  android/CouchbaseLite/src/androidTest/java/com/couchbase/lite/QueryTest.java
  shared/src/main/java/com/couchbase/lite/DataSource.java
  shared/src/main/java/com/couchbase/lite/From.java
  shared/src/main/java/com/couchbase/lite/GroupBy.java
  shared/src/main/java/com/couchbase/lite/Having.java
  shared/src/main/java/com/couchbase/lite/Join.java
  shared/src/main/java/com/couchbase/lite/Joins.java
  shared/src/main/java/com/couchbase/lite/OrderBy.java
  shared/src/main/java/com/couchbase/lite/Ordering.java
  shared/src/main/java/com/couchbase/lite/Select.java
  shared/src/main/java/com/couchbase/lite/SelectResult.java
  shared/src/main/java/com/couchbase/lite/Where.java
Labels: in progress, review, waffle:in progress

#1839 Add null check with NonNull annotations in Query Expression classes.
  shared/src/main/java/com/couchbase/lite/ArrayExpression.java
  shared/src/main/java/com/couchbase/lite/ArrayExpressionIn.java
  shared/src/main/java/com/couchbase/lite/ArrayExpressionSatisfies.java
  shared/src/main/java/com/couchbase/lite/Expression.java
  shared/src/main/java/com/couchbase/lite/FullTextExpression.java
  shared/src/main/java/com/couchbase/lite/MetaExpression.java
Labels: in progress, review, waffle:in progress

#1840 Add null check with NonNull annotations in Query Function classes.
  shared/src/main/java/com/couchbase/lite/AbstractFunction.java
  shared/src/main/java/com/couchbase/lite/ArrayFunction.java
  shared/src/main/java/com/couchbase/lite/FullTextFunction.java
Labels: in progress, review, waffle:in progress

#1841 Add null check with NonNull annotations in Query Index classes.
  shared/src/main/java/com/couchbase/lite/FullTextIndexItem.java
  shared/src/main/java/com/couchbase/lite/ValueIndexItem.java
Labels: in progress, review, waffle:in progress

#1848 fix: result test failure
  android/CouchbaseLite/src/androidTest/java/com/couchbase/lite/ResultTest.java
Labels: in progress, review, waffle:in progress

#1844 Added warnings for when file logging is disabled
  shared/src/main/java/com/couchbase/lite/AbstractDatabase.java
  shared/src/main/java/com/couchbase/lite/FileLogger.java
  shared/src/main/java/com/couchbase/lite/internal/support/Run.java
Labels: in progress, review, waffle:in progress
